# Generated by Django 4.2.7 on 2023-12-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=30)),
                ('to_location', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
