# Generated by Django 4.2.7 on 2023-12-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
