# Generated by Django 4.2.7 on 2023-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_journey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
