# Generated by Django 4.2.7 on 2023-12-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_journey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=30)),
                ('to_location', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
