# Generated by Django 4.2.7 on 2023-12-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
