# Generated by Django 4.2.7 on 2023-12-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
