# Generated by Django 4.2.7 on 2023-12-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
