# Generated by Django 4.2.7 on 2023-12-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_pk', models.CharField(max_length=30)),
                ('travels', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
