# Generated by Django 4.2.7 on 2023-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_travels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='id',
        ),
        migrations.AlterField(
            model_name='travels',
            name='journey_pk',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
